# Generated by Django 4.0.4 on 2022-10-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='classes.course'),
        ),
        migrations.AddField(
            model_name='slide',
            name='lecture',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.lecture'),
        ),
        migrations.AddField(
            model_name='tag',
            name='courses',
            field=models.ManyToManyField(related_name='tags', to='classes.course'),
        ),
    ]
